deployment:
  tasks:
    - echo "=== Deployment Started ===" >> /home/parenijj/deploy.log
    - source /home/parenijj/nodevenv/learnonlineaccounting.com/20/bin/activate && cd /home/parenijj/learnonlineaccounting.com/frontend
    - npm ci >> /home/parenijj/deploy.log 2>&1
    - npm run build >> /home/parenijj/deploy.log 2>&1
    - export DEPLOYPATH="/home/parenijj/learnonlineaccounting.com/"
    - /bin/cp -R --no-preserve=mode,ownership * "$DEPLOYPATH" >> /home/parenijj/deploy.log 2>&1
    - echo "=== Deployment Finished ===" >> /home/parenijj/deploy.log
