---
deployment:
  tasks:
    - cd frontend
    - npm ci
    - npm run build
    - export DEPLOYPATH=/home/parenijj/learnonlineaccounting.com/
    - /bin/cp -R --no-preserve=mode,ownership * $DEPLOYPATH
